### ISSUE TITLE
Not issue, just a question

### ISSUE THREAD

**Issue by AnyaPizza** [firenh/gravel_carts#1]
I know this isn't the place, but I had no idea where to go to ask. For someone such as myself who doesn't understand such things as block tags. How do I go about using these block tags to change the blocks I can use?

**Comment by firenh** [comment]
you can use a datapack to change it! you can look up plenty of tutorials online, but once you make it, make a folder inside the data folder with the path data/gravel_carts/tags/blocks/ and add a JSON file called "minecart_speed_1_5x_blocks", replacing the "1_5x" with either "2x" or "2_5x" depending on what you want, and make the JSON file in the same format as a normal tag. you can also add a JSON file called "minecart_speed_increase_under_two" for that function
